SE1705_Solution/Final_Project/Models/Slot.cs
using System;
using System.Collections.Generic;

namespace Final_Project.Models
{
    public partial class Slot
    {
        public Slot()
        {
            SlotDetails = new HashSet<SlotDetail>();
        }

        public int Id { get; set; }
        public int? MentorId { get; set; }
        public int? SubjectId { get; set; }
        public int? ClassRoomId { get; set; }
        public int SlotNumber { get; set; }
        public DateTime SlotDate { get; set; }

        public virtual ClassRoom? ClassRoom { get; set; }
        public virtual User? Mentor { get; set; }
        public virtual Subject? Subject { get; set; }
        public virtual ICollection<SlotDetail> SlotDetails { get; set; }
    }
}

SE1705_Solution/Final_Project/Pages/Schedule/SlotView.cshtml.cs
using Final_Project.Models;
using Final_Project.Repos.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Security.Cryptography.X509Certificates;

namespace Final_Project.Pages.Schedule
{
    public class SlotViewModel : PageModel
    {
        private readonly ISlotRepository _slotRepository;
        private readonly ISlotDetailRepository _slotDetailRepository;
        private readonly IUserRepository _userRepository;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly ISession _session;


        public Slot? Slot { get; set; }
        public List<SlotDetail> CurrentStudentList { get; set; } = new List<SlotDetail>();
        public List<User> AvailableMentorList { get; set; } = new List<User>();
        public List<string> ErrorMessages { get; set; } = new List<string>();

        [BindProperty(SupportsGet = true, Name = "type")]
        public int Type { get; set; }

        public User CurrentUser { get; set; }

        public SlotViewModel(ISlotRepository slotRepository, ISlotDetailRepository slotDetailRepository, IUserRepository userRepository, IHttpContextAccessor contextAccessor)
        {
            _slotRepository = slotRepository;
            _slotDetailRepository = slotDetailRepository;
            _userRepository = userRepository;
            _contextAccessor = contextAccessor;
            _session = _contextAccessor.HttpContext.Session;
        }

        public IActionResult OnGet(int slot)
        {
            if (string.IsNullOrEmpty(_session.GetString("CurrentUser"))) return RedirectToPage("/Authentication/Login");
            CurrentUser = JsonConvert.DeserializeObject<User>(_session.GetString("CurrentUser"));
            if (Type < 0 || Type > 1) Type = 0;
            var slots = _slotRepository.Gets(s => s.Id == slot);
            if(slots.Count > 0)
            {
                Slot = slots[0];
                if (Type == 0)
                {
                    var data = _slotDetailRepository.Gets(s => s.SlotId == slot);
                    CurrentStudentList = data.Where(s => s.Student?.Role == 0).ToList();
                }
                else
                {
                    var userList = _userRepository.Gets(s => s.Role == 0);
                    var slotDetailList = _slotDetailRepository.Gets(_ => true);
                    foreach (var item in userList)
                    {
                        //If student already had a subject in that slot then will not be added in the list
                        if (!slotDetailList.Any(s => s.StudentId == item.Id && s.Slot.SlotNumber == Slot.SlotNumber && s.Slot.SlotDate == Slot.SlotDate))
                        {
                            CurrentStudentList.Add(new SlotDetail { Student = item });
                        }
                    }
                }

                var mentorList = _userRepository.Gets(s => s.Role == 1);
                var slotList = _slotRepository.Gets(_ => true);
                foreach (var item in mentorList)
                {
                    //If student already had a subject in that slot then will not be added in the list
                    if (!slotList.Any(s => s.MentorId == item.Id && s.SlotNumber == Slot.SlotNumber && s.SlotDate == Slot.SlotDate))
                    {
                        AvailableMentorList.Add(item);
                    }
                }
            }
            return Page();
        }

        public void OnGetRemoveAll(int slot, int uid)
        {
            var currentSlot = _slotRepository.Get(s => s.Id == slot);
            if(currentSlot != null)
            {
                var slots = _slotRepository.Gets(s => s.SlotNumber == currentSlot.SlotNumber && s.ClassRoomId == currentSlot.ClassRoomId);
                var data = slots.Where(s => s.SlotDate.DayOfWeek.ToString().Equals(currentSlot.SlotDate.DayOfWeek.ToString()));
                foreach(var item in data)
                {
                    var slotDetail = _slotDetailRepository.Get(s => s.SlotId == item.Id && s.StudentId == uid);
                    if(slotDetail != null)
                    {
                        var result = _slotDetailRepository.Remove(slotDetail);
                        if (result == 0) ErrorMessages.Add("Remove failed");
                    }
                    else ErrorMessages.Add("Invalid slot detail id");
                }
            }
            else ErrorMessages.Add("Invalid slot id!");
            OnGet(slot);
        }

        public void OnGetAddAll(int slot, int uid)
        {
            var currentSlot = _slotRepository.Get(s => s.Id == slot);
            if (currentSlot != null)
            {
                var slots = _slotRepository.Gets(s => s.SlotNumber == currentSlot.SlotNumber && s.ClassRoomId == currentSlot.ClassRoomId);
                var data = slots.Where(s => s.SlotDate.DayOfWeek.ToString().Equals(currentSlot.SlotDate.DayOfWeek.ToString()));
                foreach(var item in data)
                {
                    var check = _slotDetailRepository.Get(s => s.StudentId == uid && s.SlotId == item.Id);
                    if(check == null)
                    {
                        var slotDetail = new SlotDetail
                        {
                            StudentId = uid,
                            SlotId = item.Id
                        };
                        var result = _slotDetailRepository.Add(slotDetail);
                        if (result == 0) ErrorMessages.Add("Add failed!");
                    }
                    else ErrorMessages.Add("This student already join this slot!");
                }
            }
            else ErrorMessages.Add("Invalid slot id!");
            OnGet(slot);
        }

        public void OnGetAdd(int slot, int uid)
        {
            var currentSlot = _slotRepository.Get(s => s.Id == slot);
            if (currentSlot != null)
            {
                var check = _slotDetailRepository.Get(s => s.StudentId == uid && s.SlotId == slot);
                if( check == null)
                {
                    var slotDetail = new SlotDetail
                    {
                        StudentId = uid,
                        SlotId = slot
                    };
                    var result = _slotDetailRepository.Add(slotDetail);
                    if (result == 0) ErrorMessages.Add("Add failed!");
                }
                else ErrorMessages.Add("This student already join this slot!");
            }
            else ErrorMessages.Add("Invalid slot id!");
            OnGet(slot);
        }

        public void OnGetRemove(int slot, int sid)
        {
            var currentSlot = _slotRepository.Get(s => s.Id == slot);
            if (currentSlot != null)
            {
                var slotDetail = _slotDetailRepository.Get(s => s.Id == sid);
                if (slotDetail != null)
                {
                    var result = _slotDetailRepository.Remove(slotDetail);
                    if (result == 0) ErrorMessages.Add("Add failed!");
                }
                else ErrorMessages.Add("Invalid slot detail id!");
            }
            else ErrorMessages.Add("Invalid slot id!");
            OnGet(slot);
        }

        public void OnGetChangeMentor(int slot, int mid)
        {
            var mentor = _userRepository.Get(s => s.Id == mid);
            if (mentor == null || mentor.Role != 1) ErrorMessages.Add("Invalid mentor ID!");
            else
            {
                var sloted = _slotRepository.Get(s => s.Id == slot);
                if (sloted != null)
                {
                    sloted.MentorId = mid;
                    _slotRepository.Update();
                }
                else ErrorMessages.Add("Invalid slot ID");
            }
            OnGet(slot);
        }
    }
}

SE1705_Solution/Final_Project/Pages/Schedule/View.cshtml.cs
using Final_Project.Models;
using Final_Project.Models.OtherModels;
using Final_Project.Repos.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Final_Project.Pages.Schedule
{
    [Authorize]
    public class ViewModel : PageModel
    {
        private readonly ICsvRepository<CsvRecord> _csvRepository;
        private readonly ISubjectRepository _subjectRepository;
        private readonly IClassroomRepository _classroomRepository;
        private readonly ISlotRepository _slotRepository;
        private readonly IConfiguration _configuration;
        private readonly IUserRepository _userRepository;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly ISession _session;

        public Dictionary<int, List<Slot>> Schedule { get; set; } = new Dictionary<int, List<Slot>>();  
        public List<string> ImportCsvErrorMessages { get; set; }

        public ViewModel(ICsvRepository<CsvRecord> csvRepos, 
            ISubjectRepository subjectRepository, 
            IClassroomRepository classroomRepository, 
            ISlotRepository slotRepository, 
            IConfiguration configuration,
            IUserRepository userRepository,
            IHttpContextAccessor contextAccessor)
        {
            _csvRepository = csvRepos;
            _subjectRepository = subjectRepository;
            _classroomRepository = classroomRepository;
            _slotRepository = slotRepository;
            _configuration = configuration;
            _userRepository = userRepository;
            _contextAccessor = contextAccessor;
            _session = _contextAccessor.HttpContext.Session;
        }

        public void OnGet()
        {
            var startDate = DateTime.Parse(_configuration["SemesterPeriod:StartDate"]);
            var data = _slotRepository.Gets(s => s.SlotDate >= startDate && s.SlotDate <= startDate.AddDays(6));
            GetSchedule(data, Schedule);
        }
        
        public async Task OnPost(IFormFile file) 
        {
            await ProcessCsvData(file);
            OnGet();
        }

        private async Task ProcessCsvData(IFormFile file)
        {
            if (file == null || file.Length == 0) return;

            ImportCsvErrorMessages = new List<string>();
            //Get all record from csv file
            var records = _csvRepository.ReadCsv(file);
            foreach (var record in records)
            {
                if (record == null) continue;

                record.TrimData();

                //Get subject by name
                var subject = _subjectRepository.GetByName(record.SubjectName);

                //if subject invalid then cancel creating new slot
                if (subject == null)
                {
                    ImportCsvErrorMessages.Add($"Invalid subject name. Error in line {record.ToString()}");
                    continue;
                }
                var subjectId = subject.Id;

                //Get classroom by code
                var classroom = _classroomRepository.GetByCode(record.ClassroomCode);

                //if classroom is invalid then cancel creating new slot
                if (classroom == null)
                {
                    ImportCsvErrorMessages.Add($"Invalid classroom code. Error in line {record.ToString()}");
                    continue;
                }
                var classroomId = classroom.Id;

                //Check mentor email
                var mentor = _userRepository.Get(s => s.Email.Equals(record.MentorEmail) && s.Role == 1);
                if (mentor == null)
                {
                    ImportCsvErrorMessages.Add($"Cannot find mentor email. Error in line {record.ToString()}");
                    continue;
                }
                var mentorId = mentor.Id;

                //Get 2 slots
                var slotDates = record.GetSlotDate();

                //if no slot counted then csv mismatch form
                if (slotDates.Count == 0)
                {
                    ImportCsvErrorMessages.Add($"Cannot split slots. Error in line {record.ToString()}");
                    continue;
                }
                foreach (var slotDate in slotDates)
                {
                    int count = 0;
                    DateTime startDate = DateTime.Parse(_configuration["SemesterPeriod:StartDate"]);

                    //If slot is available then add new Slot
                    if (IsSlotAvailable(slotDate.slotNum, classroom.Id, slotDate.Day))
                    {
                        //Check if mentor is available for this slot
                        if (!IsUserAvailable(mentorId, slotDate.slotNum, slotDate.Day))
                        {
                            ImportCsvErrorMessages.Add($"Mentor is not available for slot {slotDate.slotNum} on {slotDate.Day}. Error in line {record.ToString()}");
                            continue;
                        }
                        while (count < (subject.Slot/2))
                        {
                            if (startDate.DayOfWeek.ToString().Equals(slotDate.Day))
                            {
                                var slot = new Slot
                                {
                                    SubjectId = subjectId,
                                    ClassRoomId = classroomId,
                                    SlotDate = startDate,
                                    SlotNumber = slotDate.slotNum,
                                    MentorId = mentorId
                                };
                                var result = await _slotRepository.CreateAsync(slot);
                                if (result == 0) ImportCsvErrorMessages.Add($"Cannot add new slot {slotDate.slotNum} on {slotDate.Day}. Error in line {record.ToString()}");
                                count++;
                            }
                            startDate = startDate.AddDays(1);
                        }
                    }
                    else ImportCsvErrorMessages.Add($"Slot {slotDate.slotNum} on {slotDate.Day} is not available. Error in line {record.ToString()}");
                }
            }
        }

        private bool IsSlotAvailable(int slotNum, int classroomId, string slotDay)
        {
            var slot = _slotRepository.Gets(s => s.SlotNumber == slotNum && s.ClassRoomId == classroomId);
            var data = slot.Find(s => s.SlotDate.DayOfWeek.ToString().Equals(slotDay));
            return data == null;
        }

        private void GetSchedule(List<Slot> data, Dictionary<int, List<Slot>> schedule)
        {
            var mondays = new List<Slot>();
            var tuesdays = new List<Slot>();
            var wednesdays = new List<Slot>();
            var thursdays = new List<Slot>();
            var fridays = new List<Slot>();
            var saturdays = new List<Slot>();
            var sundays = new List<Slot>();

            foreach(var item in data)
            {
                switch(item.SlotDate.DayOfWeek.ToString())
                {
                    case "Monday":
                        {
                            mondays.Add(item);
                            break;
                        }
                    case "Tuesday":
                        {
                            tuesdays.Add(item);
                            break;
                        }
                    case "Wednesday":
                        {
                            wednesdays.Add(item);
                            break;
                        }
                    case "Thursday":
                        {
                            thursdays.Add(item);
                            break;
                        }
                    case "Friday":
                        {
                            fridays.Add(item);
                            break;
                        }
                    case "Saturday":
                        {
                            saturdays.Add(item);
                            break;
                        }
                    case "Sunday":
                        {
                            sundays.Add(item);
                            break;
                        }
                }
            }

            schedule.Add(2, mondays);
            schedule.Add(3, tuesdays);
            schedule.Add(4, wednesdays);
            schedule.Add(5, thursdays);
            schedule.Add(6, fridays);
            schedule.Add(7, saturdays);
            schedule.Add(8, sundays);
        }

        private bool IsUserAvailable(int mentorId, int slotNum, string slotDay)
        {
            var slot = _slotRepository.Gets(s => s.SlotNumber == slotNum && s.MentorId == mentorId);
            if(slot.Count == 0) return true;
            var data = slot.Find(s => s.SlotDate.DayOfWeek.ToString().Equals(slotDay));
            return data == null;
        }
    }
}

SE1705_Solution/Final_Project/Pages/Schedule/SlotView.cshtml
@page
@model Final_Project.Pages.Schedule.SlotViewModel
@{
}

<a class="btn" asp-page="@(Model.CurrentUser.Role == 2 ? "/Schedule/View" : "/Home/UserHome")">Return View</a>
<br />
<h1>Slot Details</h1><br />

<div>
    <p><span><strong>Subject Name:</strong></span> @Model.Slot.Subject.Name</p>
    <p><span><strong>Classroom:</strong></span> @Model.Slot.ClassRoom.Code</p>
    <p><span><strong>Slot:</strong></span> @Model.Slot.SlotNumber</p>
    <p><span><strong>Date:</strong></span> @Model.Slot.SlotDate.ToShortDateString()</p>
    <p><span><strong>Mentor:</strong></span> @Model.Slot.Mentor.FullName</p>
</div><br />
<a id="change_mentor_btn" class="btn">Change Mentor</a><br />
<div id="mentor_list">
    @if(Model.AvailableMentorList.Count == 0)
    {
        <p>No mentor is available for this slot!</p>
    }
    else
    {
        <table>
            <tr>
                <th>ID</th>
                <th>Email</th>
                <th>FullName</th>
            </tr>
            @foreach (var item in Model.AvailableMentorList)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Email</td>
                    <td>@item.FullName</td>
                    <td><a asp-page-handler="changementor" asp-route-slot="@Model.Slot.Id" asp-route-mid="@item.Id">Replace</a></td>
                </tr>
            }
        </table>

        <br />
    }
</div>

<h2>List Student</h2>
@if(Model.CurrentUser.Role == 2)
{
    <div>
        <a asp-route-slot="@Model.Slot.Id" class="btn">Current Student</a>
        <a asp-route-type="1" asp-route-slot="@Model.Slot.Id" class="btn">Add Student</a>
    </div>
}
<br />
@if(Model.CurrentStudentList.Count == 0)
{
    <p>This slot currently had no student yet!</p>
}
else
{
    <table>
        <tr>
            <th>ID</th>
            <th>Email</th>
            <th>FullName</th>
        </tr>
        @foreach (var item in Model.CurrentStudentList)
        {
            <tr>
                <td>@item.Student.Id</td>
                <td>@item.Student.Email</td>
                <td>@item.Student.FullName</td>
                @if(Model.CurrentUser.Role == 2)
                {
                    if (Model.Type == 0)
                    {
                        <td><a asp-page-handler="remove" asp-route-slot="@Model.Slot.Id" asp-route-type="@Model.Type" asp-route-sid="@item.Id">Remove for this</a></td>
                        <td><a asp-page-handler="removeall" asp-route-slot="@Model.Slot.Id" asp-route-type="@Model.Type" asp-route-uid="@item.Student.Id">Remove for all</a></td>
                    }
                    else
                    {
                        <td><a asp-page-handler="add" asp-route-slot="@Model.Slot.Id" asp-route-type="@Model.Type" asp-route-uid="@item.Student.Id">Add to this</a></td>
                        <td><a asp-page-handler="addall" asp-route-slot="@Model.Slot.Id" asp-route-type="@Model.Type" asp-route-uid="@item.Student.Id">Add to all</a></td>
                    }
                }
            </tr>
        }
    </table>
}
<br />
@foreach(var item in Model.ErrorMessages)
{
    <p style="color: red">@item</p>
}

<style>
    p{
        line-height: 0.5;
    }
    .btn {
        border: 1px solid black;
        border-radius: 5px;
        padding: 5px;
        min-height: 20px;
        width: auto;
    }

        .btn:hover {
            background: aqua;
        }
    th,td{
        padding: 10px;
    }
    #mentor_list{
        display: none;
    }
</style>

<script>
    let status = "block";
    document.getElementById("change_mentor_btn").addEventListener("click", function(){
        var area = document.getElementById("mentor_list");
        area.style.display = status;
        if(status === "none") status = "block";
        else status = "none";
    })
</script>

SE1705_Solution/Final_Project/Pages/Schedule/View.cshtml
@page
@model Final_Project.Pages.Schedule.ViewModel
@using Models
@{
} 
<a asp-page="/Home/AdminHome" class="btn">Return</a>
<h1>List of slot</h1>
<table>
    <tr>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
        <th>Saturday</th>
        <th>Sunday</th>
    </tr>
    @{
        var max = GetMaxListCount(Model.Schedule);
        for(int i = 0; i < max; i++)
        {
            <tr>
                @for(int j = 2; j <= 8; j++)
                {
                    var data = GetData(Model.Schedule.GetValueOrDefault(j), i);
                    if(data == null)
                    {
                        <td></td>
                    }
                    else
                    {
                        <td>
                            <div>
                                <span style="color: dodgerblue"><a asp-page="/Schedule/SlotView" asp-route-slot="@data.Id">@data.Subject.Name</a></span><br>
                                <span style="font-size: 12px;">Room: @data.ClassRoom.Code</span><br>
                                <span style="font-size: 12px;">Slot: @data.SlotNumber</span>
                            </div>
                        </td>
                    }
                }
            </tr>
        }
    }
</table><br />

<h2>Import Schedule</h2>
<div class="container">
    <div class="col-4">
        <form method="post" enctype="multipart/form-data">
            <input type="file" name="file" /><br>
            <button type="submit">Import Data</button>
        </form>
        <br />
    </div>

    @if (Model.ImportCsvErrorMessages != null)
    {
        <div class="col-8">
            @foreach (var item in Model.ImportCsvErrorMessages)
            {
            <p style="color: red">@item</p>
            }
        </div>
    }
</div>

@functions{
    public Slot? GetData(List<Slot>? data, int index)
    {
        if (data == null) return null;
        return index < data.Count ? data[index] : null;
    }

    public int GetMaxListCount(Dictionary<int, List<Slot>> data)
    {
        var lists = new List<List<Slot>>(data.Values);
        int maxCount = 0;

        foreach (var list in lists)
        {
            if (list.Count > maxCount)
            {
                maxCount = list.Count;
            }
        }

        return maxCount;
    }
}

<style>
    .btn {
        border: 1px solid black;
        border-radius: 5px;
        padding: 5px;
        min-height: 20px;
        width: auto;
    }

        .btn:hover {
            background: aqua;
        }
    p{
        line-height: 0.5;
    }
    button {
        margin-top: 10px;
        min-width: 150px;
        min-height: 20px;
        outline: none;
        border-radius: 5px;
        border: 1px solid black;
        padding: 2px;
    }

        button:hover {
            background: aqua;
        }
    a{
        text-decoration: none;
        cursor: pointer;
    }
    a:hover{
        color: blue;
    }
</style>